---
title: "gdp_shiny_app"
author: "Ben Tanenbaum"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{r, echo = FALSE, message = FALSE}

library(tidyverse)
library(gapminder)
library(readr)
library(shiny)
library(ggplot2)

```

```{r}
ui <- fluidPage(

      sliderInput(inputId="slider",
                  label="sliderInput",
                  min=1961, max=2023, value=c(1961, 2023)),
      plotOutput("gdp_line")
)
```

```{r}

server <- function(input, output, session) {
  gdp2 <- read_csv("gdp2.csv", skip = 3)
  gdp2 <- subset(gdp2, `Country Code` == 'USA' | `Country Code` == 'CHN' | `Country Code` == 'IND' | `Country Code` == 'WLD')
  gdp2 <- gdp2 %>% mutate(`Country Name` = str_replace(`Country Name`, "World", "Global"))
  gdp2 <- gdp2 %>% pivot_longer(cols=c('1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023'), names_to = 'Year', values_to = 'GDP')
gdp2$Year <- as.numeric(gdp2$Year)
gdp2$GDP <- gdp2$GDP/1e12 

  filtered_gdp <- reactive({
    gdp2 %>% filter(Year >= input$slider[1] & Year <= input$slider[2])
  })

  # draw the plot 
  output$gdp_line <- renderPlot({ ggplot(filtered_gdp(), aes(x = `Year`, y = `GDP`, group = `Country Name`, color = `Country Name`)) + geom_line() + ggtitle("How have GDPs of China, India, the United States, \nand the World Changed Over Time?") + ylab("GDP (constant 2017 international $)") + theme(legend.title = element_blank()) + scale_color_manual(limits=c('Global', 'China', 'United States', 'India'), values=c('darkgreen', 'red', 'purple', 'blue')) + scale_y_continuous(labels = scales::label_number(suffix = " trillion", accuracy = 1.0))
  })
}

shinyApp(ui, server)

```
